# The URL the site will be built for
base_url = "https://naps62.com"

title = "Miguel Palhas | @naps62"
description = "Software Developer | Elixir | Ruby | Rust | DevOps | Chess"
default_language = "en"

compile_sass = true
highlight_code = true
build_search_index = true

theme = "naps62-serene"
highlight_theme = "base16-ocean-light"
generate_feed = true
rss_limit = 20
taxonomies = [{ name = "tags" }, { name = "categories" }]

[extra]
name = "Miguel Palhas"
id = "naps62"
bio = ""
links = []
profile = "photo.png"
avatar = "img/photo.png"
website = "naps62.com"
twitter = "naps62"
github = "naps62"
email = "mpalhas@gmail.com"
goatcounter = "naps62"

nav_separator = "::"

display_id = false
projects_page = false
blog_categorized = false
blur_effect = true

toc = true
comment = false

outdate_alert = false
outdate_alert_days = 120
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "© 2023 <your-name>"
footer_credits = true
