name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
