name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set git Identity
        run: |
          git config --global user.name "Miguel Palhas"
          git config --global user.email "mpalhas@gmail.com"

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            v1-${{ runner.os }}

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
