name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        uses: naps62/zola-deploy-action@master
        env:
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}
