name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: alpine:edge

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install zola
        run: |
          echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
          apk add zola@testing

      - name: Build
        run: zola build

      - name: Push
        run: |
          cd public
          git init
          git config user.name "GitHub Actions"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add .

          git commit -m "Automatic deploy"
          git push --force "https://${{ secrets.DEPLOY_TOKEN }}@github.com/naps62.github.io.git" master:master
