name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.GITHUB_DEPLOY_TOKEN }}
