name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set git identity
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "mpalhas@gmail.com"

      - name: Set git remote
        run: |
          git remote set-url origin https://naps62:${{ secrets.GITHUB_TOKEN }}@github.com/naps62/naps62.github.io

      - name: Setup Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: v2-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            v1-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
            v1-${{ runner.os }}

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy
